name: letagas
description: A new Flutter project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- Added Packages ---
  get: ^4.6.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.9.1
  flutter_animate: ^4.5.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0   # upgraded

flutter:
  uses-material-design: true
  assets:
    - assets/images/
